### ISSUE TITLE
Message submission broken

### ISSUE THREAD

**Issue by SamBartrum** [markharley/anarxiv#4]
Message submission is now no longer working. No idea why. 

Getting "NOT NULL constraint failed: anarxiv_app_post.user_id" error. So I think this may be linked to Jack's work.

**Comment by elmsly** [comment]
> On 26 Nov 2015, at 21:20, SamBartrum <notifications@github.com> wrote:
> 
> Message submission is now no longer working. No idea why.

Looks like the Post model takes a one-to-one relation to a user-id. The problem is on line 192 in views.py, which now needs to get a username from the request and pass that through to the Post constructor.

I don’t know how user IDs are handled in the rest of the project. Is this known from context? Is there a session cookie for each user?

**Comment by SamBartrum** [comment]
Yeah I figured that was the issue. You also need to attach the post to a specific paper object (which is straightforward). Leaving the user attribute out of the model works for now.

I'm not sure how Users will work (they are not really implemented yet - just the models set up), I'll have to think about it. I imagine you'll have to have some sort of user-id which is passed back and forth between the server and the client through post requests.

**Comment by markharley** [comment]
If I remember correctly, django stores the user id in the cookies by default. The request object has a property request.user which returns a user object.

**Comment by SamBartrum** [comment]
Flip, that is useful.

**Comment by JackMedley** [comment]
Shall we set up a slack page for anarxiv rather than using email?


> On 27 Nov 2015, at 12:34, SamBartrum <notifications@github.com> wrote:
> 
> Flip, that is useful.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/markharley/anarxiv/issues/4#issuecomment-160130995>.
> 


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.
